"""empty message

Revision ID: 922346e0c870
Revises: 
Create Date: 2021-03-16 02:25:31.139059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922346e0c870'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('housing_queue',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('residents',
    sa.Column('rit_username', sa.String(length=7), nullable=False),
    sa.Column('full_name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('rit_username')
    )
    op.create_table('rooms',
    sa.Column('room_number', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('room_number')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rooms')
    op.drop_table('residents')
    op.drop_table('housing_queue')
    # ### end Alembic commands ###
